### ISSUE TITLE
ToApproximateAgeString() result is prefixed with minus sign.

### ISSUE THREAD

**Issue by marknotgeorge** [exceptionless/Exceptionless.DateTimeExtensions#1]
The following code fragment
`var now = DateTime.Now;
 var oneHourAway = now.AddHours(1);
 Debug.WriteLine(oneHourAway.ToApproximateAgeString());`

outputs the following:
`-59 minutes from now`

Is this by design?

**Comment by niemyjski** [comment]
That seems like a bug, could you please create a pr and test for this. That would be a huge help!
